language: python
python:
  - "3.6"
# command to install dependencies
install:
  # Install all the other dependencies
  - pip install -e .[tests] -q -q
# command to run tests
script: py.test  --cov-report=term-missing --cov=pyjet tests/
# Run the coverage
aftersuccess:
  - codecov
  - coveralls
