language: python
python:
  - "3.5"
# command to install dependencies
install:
  # Install PyTorch
  - pip install -q http://download.pytorch.org/whl/cu80/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl
  # Install all the other dependencies
  - pip install -e .[tests]
# command to run tests
script: py.test tests/ -v --cov pyjet --cov-report term-missing
# Run the coverage
aftersuccess:
  - coveralls
